name: Twitter Bot Scheduler

on:
  schedule:
    # 7 scheduled runs per day (IST) with ±15 min random delay
    # 5:00 PM  → 11:30 UTC
    - cron: "30 11 * * *"
    # 6:40 PM → 13:10 UTC
    - cron: "10 13 * * *"
    # 8:00 PM → 14:30 UTC
    - cron: "30 14 * * *"
    # 9:10 PM → 15:40 UTC
    - cron: "40 15 * * *"
    # 9:50 PM → 16:20 UTC
    - cron: "20 16 * * *"
    # 10:30 PM → 17:00 UTC
    - cron: "0 17 * * *"
    # 11:00 PM → 17:30 UTC
    - cron: "30 17 * * *"

  workflow_dispatch:
    inputs:
      mode:
        description: "Mode to run (fetch or reply)"
        required: false
        default: fetch

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tweepy apify-client requests pytz

      - name: Log current time and apply random delay
        run: |
          echo "🕒 Current UTC: $(date -u)"
          echo "🕒 Current IST: $(TZ='Asia/Kolkata' date)"
          echo "⚙️ Applying random delay up to ±15 minutes..."
          delay=$(( (RANDOM % 1800) - 900 ))  # -900 to +900 seconds
          if [ $delay -gt 0 ]; then
            echo "⏳ Sleeping for $delay seconds (~$((delay/60)) min)..."
            sleep $delay
          else
            echo "⚡ Negative offset ($delay s) — skipping wait."
          fi

      - name: Run bot
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API: ${{ secrets.PERPLEXITY_API }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: |
          echo "🚀 Running apyfi1.py..."
          python -u apyfi1.py
