name: Twitter Bot Scheduler

on:
  schedule:
    # Step 1 - Fetch new tweets + first reply
    - cron: "30 3,7,11,15 * * *"   # 9:00, 13:00, 17:00, 21:00 IST
    # Step 2 - Reply #1 (20 mins later)
    - cron: "50 3,7,11,15 * * *"
    # Step 3 - Reply #2 (40 mins later)
    - cron: "10 4,8,12,16 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install tweepy apify-client requests

      - name: Run bot - Fetch
        if: github.event_name == 'schedule' && (github.event.schedule == '30 3,7,11,15 * * *')
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API: ${{ secrets.PERPLEXITY_API }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          MODE: fetch
        run: python apyfi.py

      - name: Run bot - Reply
        if: github.event_name == 'schedule' && (github.event.schedule != '30 3,7,11,15 * * *')
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API: ${{ secrets.PERPLEXITY_API }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          MODE: reply
        run: python apyfi.py
