name: Twitter Bot Scheduler

on:
  schedule:
    # ---------------- Fetch ----------------
    - cron: "0 6 * * *"   # 11:30 IST
    - cron: "0 9 * * *"   # 14:30 IST
    - cron: "0 12 * * *"  # 17:30 IST
    - cron: "0 13 * * *"  # 18:30 IST
    - cron: "0 17 * * *"  # 22:30 IST

    # ---------------- Reply #1 (+20 min) ----------------
    - cron: "20 6 * * *"  # 11:50 IST
    - cron: "20 9 * * *"  # 14:50 IST
    - cron: "20 12 * * *" # 17:50 IST
    - cron: "20 13 * * *" # 18:50 IST
    - cron: "20 17 * * *" # 22:50 IST

    # ---------------- Reply #2 (+40 min) ----------------
    - cron: "40 6 * * *"  # 12:10 IST
    - cron: "40 9 * * *"  # 15:10 IST
    - cron: "40 12 * * *" # 18:10 IST
    - cron: "40 13 * * *" # 19:10 IST
    - cron: "40 17 * * *" # 23:10 IST

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install tweepy apify-client requests pytz

      # ---------------- Fetch Mode ----------------
      - name: Run Fetch
        if: |
          github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'fetch' ||
          github.event_name == 'schedule' && contains('0 6,0 9,0 12,0 13,0 17', github.event.schedule)
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API: ${{ secrets.PERPLEXITY_API }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          MODE: fetch
        run: python apyfi.py

      # ---------------- Reply Mode ----------------
      - name: Run Reply
        if: |
          github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'reply' ||
          github.event_name == 'schedule' && contains('20 6,20 9,20 12,20 13,20 17,40 6,40 9,40 12,40 13,40 17', github.event.schedule)
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API: ${{ secrets.PERPLEXITY_API }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          MODE: reply
        run: python apyfi.py
