name: Twitter Bot Scheduler

on:
  schedule:
    # Step 1 - Fetch new tweets + first reply
    - cron: "30 3,7,11,15 * * *"   # 9:00, 13:00, 17:00, 21:00 IST
    # Step 2 - Reply #1 (20 mins later)
    - cron: "50 3,7,11,15 * * *"
    # Step 3 - Reply #2 (40 mins later)
    - cron: "10 4,8,12,16 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install tweepy apify-client requests

      - name: Run bot
        env:
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          MODE: ${{ github.event.schedule == '30 3,7,11,15 * * *' && 'fetch' || 'reply' }}
        run: python apyfi.py
