name: Hourly Posting Bot

on:
  schedule:
    # 10 AM to 1 AM IST = 04:30 to 19:30 UTC
    - cron: '30 4-19 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install tweepy googletrans==4.0.0-rc1 transformers sentencepiece

      - name: Run posting bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python scrape_post_bot.py
