name: Twitter Bot (FetchPost Hourly)

on:
  schedule:
    # Run every hour between 9:00 AM and 1:00 AM IST
    # IST = UTC + 5:30 → 9:00 AM IST = 03:30 UTC, 1:00 AM IST = 19:30 UTC
    - cron: '30 3-19 * * *'  # every hour 09:00–01:00 IST
  workflow_dispatch:

jobs:
  tweet-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests beautifulsoup4 lxml googletrans==4.0.0-rc1

      - name: Set environment variables
        run: |
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "API_SECRET=${{ secrets.API_SECRET }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> $GITHUB_ENV

      - name: Run fetch and post
        run: |
          python fetchpost1.py
