- name: Run bot script
  env:
    API_KEY: ${{ secrets.API_KEY }}
    API_SECRET: ${{ secrets.API_SECRET }}
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  run: |
    python political_live_archive_bot.py
